repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    exclude: "mkdocs.yml"
  - id: end-of-file-fixer
    exclude: ".*.svg"
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer
  - id: detect-private-key
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.278
  hooks:
    - id: ruff
      exclude: ^train/ # This is temporary ...
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.9
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
